Use cascade operators to call register methods
vanlooverenkoen/kiwi pull request #72
Opened 2021-06-26 17:22 UTC by kennethnym

This PR address the issue that register methods are called on repeated `container` reference. According to Effective Dart's recommendation, repeated methods calls on the same target should be done using the cascade operator `..` on a single target reference. For example, instead of calling register methods like so:
```dart
final KiwiContainer container = KiwiContainer();
container.registerFactory();
container.registerSingleton();
```
it is cleaner to use the cascade operator on a single `container` reference:
```
container
  ..registerFactory()
  ..registerSingleton();
```

By the way, `build.yaml` is giving me problems when running build_runner:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 318ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 4.7s

[SEVERE] Failed to parse `build.yaml` for flutter_example.

If you believe you have gotten this message in error, especially if using a new
feature, you may need to run `pub run build_runner clean` and then rebuild.

Invalid argument(s): line 4, column 7 of build.yaml: Unsupported value for "builders". type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
  ╷
4 │       kiwi:
  │       ^^^^^
  ╵
pub finished with exit code 78
```
The issue can be fixed by commenting out the content in `build.yaml`. Normally, a `build.yaml` is not required in a project that only consumes build runners such as `kiwi_generator`, so I think the step of adding a `build.yaml` to projects that use `kiwi` isn't necessary and should be removed.

2021-07-08 07:34 UTC, vanlooverenkoen requested changes
Thanks for your contribution. Instead of commenting we should just remove the build.yaml as you already stated.

2021-07-08 07:35 UTC, vanlooverenkoen commented
My personal account did not yet have a travis plan. So I added that as well. Your next commit will trigger a travis CI build for validation checks. if that completes successfully I will approve, merge & create a new build

2021-07-14 09:54 UTC, vanlooverenkoen commented
@kennethnym can you fix my pr comments?

2021-07-14 09:55 UTC, kennethnym commented
Sorry, forgot about this. I will fix it asap in my free time.

2021-07-14 09:56 UTC, vanlooverenkoen commented
Perfect. Thanks

2021-07-15 17:31 UTC, vanlooverenkoen approved these changes

2021-07-15 17:31 UTC, merged

2021-07-15 17:49 UTC, vanlooverenkoen commented
3.0.1 of the kiwi_generator is released